version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    command: python -m bot.main
    volumes:
      - .:/app

  scheduler:
    build:
      context: .
    depends_on:
      - bot
      - postgres
    env_file:
      - .env
    command: python scheduler/run_scheduler.py
    volumes:
      - .:/app

  admin_panel:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    container_name: admin_panel
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./admin_panel/exports:/app/admin_panel/exports

  appium1:
    build:
      context: .
      dockerfile: Dockerfile.android-appium
    container_name: appium1
    privileged: true
    ports:
      - "4723:4723"
      - "6080:6080"
    environment:
      DEVICE_NAME: Pixel_5_API_30
      APPIUM: true
    volumes:
      - .:/app

volumes:
  postgres_data:
