version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://botuser:botpass@postgres:5432/botdb
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - .:/app
    command: python -m bot.main  # адаптируй под свою структуру

volumes:
  postgres_data:
