version: "3.9"

services:
  admin_panel:
    build:
      context: .
      dockerfile: admin_panel/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_ID=${ADMIN_ID}
    depends_on:
      - postgres

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    command: ["python", "-m", "scheduler.combined_scheduler"]
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
