version: '3.9'

services:

  scheduler:
    build: .
    command: python run_scheduler.py
    depends_on:
      - bot
      - postgres

  view-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run_scheduler_view.py
    depends_on:
      - bot
      - postgres

  appium1:
    build:
      context: .
      dockerfile: Dockerfile.android-appium
    container_name: appium1
    privileged: true
    ports:
      - "4723:4723"
      - "6080:6080"
    environment:
      DEVICE_NAME: Pixel_5_API_30
      APPIUM: true
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env 
    environment:
      DATABASE_URL: postgresql+asyncpg://botuser:botpass@postgres:5432/botdb
    volumes:
      - .:/app
    command: python -m bot.main

volumes:
  postgres_data:
