"""add ViewTask

Revision ID: 04fb2d63e576
Revises: dbdf38f94541
Create Date: 2025-05-09 20:17:31.438624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fb2d63e576'
down_revision: Union[str, None] = 'dbdf38f94541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view_tasks', sa.Column('target_profiles', sa.String(), nullable=True))
    op.drop_column('view_tasks', 'target_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view_tasks', sa.Column('target_profile', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('view_tasks', 'target_profiles')
    # ### end Alembic commands ###
