"""Add instagram_login to Subscriber

Revision ID: 14ede80f1d88
Revises: f476084f3824
Create Date: 2025-05-09 19:53:13.577266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14ede80f1d88'
down_revision: Union[str, None] = 'f476084f3824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('instagram_login', sa.String(), nullable=False))
    op.add_column('subscribers', sa.Column('instagram_password', sa.String(), nullable=False))
    op.alter_column('subscribers', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.drop_column('subscribers', 'username')
    op.drop_column('subscribers', 'joined_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscribers', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('subscribers', 'telegram_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.drop_column('subscribers', 'instagram_password')
    op.drop_column('subscribers', 'instagram_login')
    # ### end Alembic commands ###
