"""Add ViewResult relation to ViewTask

Revision ID: 713ea0faa762
Revises: 04fb2d63e576
Create Date: 2025-05-09 20:22:57.989156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713ea0faa762'
down_revision: Union[str, None] = '04fb2d63e576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view_results', sa.Column('view_task_id', sa.Integer(), nullable=True))
    op.add_column('view_results', sa.Column('profile_viewed', sa.String(), nullable=True))
    op.add_column('view_results', sa.Column('viewer_account', sa.String(), nullable=True))
    op.drop_constraint('view_results_task_id_fkey', 'view_results', type_='foreignkey')
    op.create_foreign_key(None, 'view_results', 'view_tasks', ['view_task_id'], ['id'])
    op.drop_column('view_results', 'account')
    op.drop_column('view_results', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view_results', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('view_results', sa.Column('account', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'view_results', type_='foreignkey')
    op.create_foreign_key('view_results_task_id_fkey', 'view_results', 'view_tasks', ['task_id'], ['id'])
    op.drop_column('view_results', 'viewer_account')
    op.drop_column('view_results', 'profile_viewed')
    op.drop_column('view_results', 'view_task_id')
    # ### end Alembic commands ###
