"""add subscriber_id to ReelsTask

Revision ID: dbdf38f94541
Revises: 14ede80f1d88
Create Date: 2025-05-09 20:14:28.376567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbdf38f94541'
down_revision: Union[str, None] = '14ede80f1d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reels_tasks', sa.Column('subscriber_id', sa.Integer(), nullable=True))
    op.alter_column('reels_tasks', 'post_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_foreign_key(None, 'reels_tasks', 'subscribers', ['subscriber_id'], ['id'])
    op.drop_column('reels_tasks', 'instagram_login')
    op.drop_column('reels_tasks', 'instagram_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reels_tasks', sa.Column('instagram_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reels_tasks', sa.Column('instagram_login', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reels_tasks', type_='foreignkey')
    op.alter_column('reels_tasks', 'post_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('reels_tasks', 'subscriber_id')
    # ### end Alembic commands ###
