"""initial

Revision ID: f476084f3824
Revises: 
Create Date: 2025-05-09 19:36:27.206081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f476084f3824'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('instagram_login', sa.String(), nullable=False))
    op.add_column('subscribers', sa.Column('instagram_password', sa.String(), nullable=False))
    op.add_column('subscribers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('subscribers', 'username')
    op.drop_column('subscribers', 'joined_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscribers', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subscribers', 'created_at')
    op.drop_column('subscribers', 'instagram_password')
    op.drop_column('subscribers', 'instagram_login')
    # ### end Alembic commands ###
